#ifndef SCOOTER_UTILS_VERSION_H
#define SCOOTER_UTILS_VERSION_H

#define SCOOTER_UTILS_VERSION_MAJOR 1
#define SCOOTER_UTILS_VERSION_MINOR 2
#define SCOOTER_UTILS_VERSION_PATCH 0

#endif // SCOOTER_UTILS_VERSION_H
